---
server.name: kibana
server.host: "0"
elasticsearch.hosts: [http://elasticsearch:9200]

xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.encryptedSavedObjects.encryptionKey: 939ec10004d87e2a2bc0c400345537bf323842345c251390400fd1da3f6c4431
